server:
  port: 8585

spring:
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chengfeng1_5?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        login-username: admin
        login-password: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
#    ehcache:
#      config: classpath:/ehcache.xml
  redis:
    database: 1
    host: 47.95.244.237
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
    mongodb:
      uri: mongodb://localhost/chengfeng
      username: chengfeng
      password: password
  mail:
    host: smtp.qq.com
    username: 2375872953@qq.com
    password: wmsmfzchmzpjdiai
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.beautifulsoup.chengfeng.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.beautifulsoup.chengfeng.dao: DEBUG
    com.beautifulsoup.chengfeng.service.impl: DEBUG

memcached:
  servers: 47.95.244.237:9999
  # 连接池
  poolSize: 10
  #操作超时时间
  opTimeout: 6000

rabbitmq:
  addresses: 127.0.0.1
  port: 5672
  virtualHost: /
  username: guest
  password: guest

